version: '3.1'
services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Calamardo99!
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 127.0.0.1:27017:27017      
  redis:    
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './dockervolume/redis'  
    ports:
      - 6379:6379    